---
abstract: 'A Node style event Role for Moose'
author:
  - 'Rebecca Turner <becca@referencethis.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Event
requires:
  Any::Moose: 0
  Event::Wrappable: 0
resources:
  bugtracker: https://github.com/iarna/MooseX-Event/issues
  homepage: https://github.com/iarna/MooseX-Event
  repository: https://github.com/iarna/MooseX-Event.git
version: 0.3.0_1
